[versions]
# libraries
junit = "4.13.2"
tinify = "1.8.3"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.0.0"
kotlin = "1.9.24"
kover = "0.8.1"
qodana = "2024.1.5"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
tinify = { group = "com.tinify", name = "tinify", version.ref = "tinify" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
